name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [11]
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
            - name: Configure git
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
            - name: set executable permissions
              run: |
                  chmod +x patchwork
                  chmod +x scripts/*
            - name: Patch and build
              run: |
                  ./patchwork build
            - name: Upload a build artifact
              uses: actions/upload-artifact@v3
              with:
                name: release apk cuz i dont have a pc cnat bulid
                path: meeksx/build/app/build/outputs/apk/release/app-release.apk
